// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://abjfnstanugknjqjynlw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFiamZuc3RhbnVna25qcWp5bmx3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYyNTgyNDgsImV4cCI6MjA3MTgzNDI0OH0.ePh11YU6lYwDIJSuJ_mx3g576L-7NKwJdLPOznZMYnM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});